from openai import OpenAI
import base64
import os
import pandas as pd

client = OpenAI()

folder_paths_raw = ['Dataset/Real_painting']
folder_paths = [folder_path for folder_path in folder_paths_raw]

def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

def get_png_files(path):
    return [f for f in os.listdir(path) if f.endswith('.png')]

prompt = '''In one short sentence, describe the scene, its main elements, and the technique used to create the following image.'''

for folder_path,raw_path in zip(folder_paths,folder_paths_raw):
    df = pd.DataFrame(columns=['0','1','2','3','4','5','6','7','8','9'])

    # get folder paths, each folder contains 10 pngs of the corresponding mimic paintings generated by the LLM in the corresponding artist name
    full_folder_paths = [
        os.path.join(folder_path, name)
        for name in os.listdir(folder_path)
        if os.path.isdir(os.path.join(folder_path, name))
    ]
    for direct_path in full_folder_paths:
        png_files = get_png_files(direct_path)
        for file_name in png_files:
            image_path = os.path.join(direct_path, file_name)
            base64_image = encode_image(image_path)
            response = client.chat.completions.create(
                model='gpt-4.1-2025-04-14',
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": prompt},
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": f"data:image/png;base64,{base64_image}"
                                }
                            }
                        ]
                    }
                ],
                max_tokens=500,
                temperature=0,
            )
            artist_name = os.path.basename(direct_path)

            df.at[artist_name, file_name.replace('.png','')] = response.choices[0].message.content
            print(response.choices[0].message.content)

    df.to_excel(f'Painting_generate_prompt_short.xlsx', index=True, engine='openpyxl')

